version: '3.3'
services:
 web:
  build:
   context: ./php
   dockerfile: Dockerfile
  container_name: php73
  volumes:
    - ./php:/var/www/html/
  ports:
    - 8080:80 
 db:
  container_name: mysql_8
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: netsim.db
   MYSQL_USER: devuser
   MYSQL_PASSWORD: devpass
  ports:
    - 6033:3306
